### ISSUE TITLE
如果el-table-column type="index"或者 type="selection"展示会有问题

### ISSUE THREAD

**Issue by thinkwithlinc** [aweikalee/element-plus-table-proxy-demo#1]
会错开一列，有方法可以处理吗

**Comment by aweikalee** [comment]
能更详细地描述一下问题吗？我不太理解“错开一列”指的是什么。

**Comment by thinkwithlinc** [comment]
假设第一列是这种
`    <MyTable v-if="show" :data="data" ref="table" max-height="400" :style="{ maxWidth: '500px' }">
      <el-table-column prop="selection" type="selection" label="选择" min-width="50" />`


把第一列多选框隐藏掉后

![image](https://user-images.githubusercontent.com/2087012/150072774-196b00b3-8fcc-45c8-9ba6-3f9c59a68d7a.png)

**Comment by thinkwithlinc** [comment]
如果有一列使用了router-link，在隐藏后再放开跳转链接就消失了，是不是要重新渲染一下el-table

**Comment by aweikalee** [comment]
*el-table* 是通过 *el-table-column* 的 `onMounted` 与 `onBeforeUnmount` 来创建与销毁列数据的。
而 Vue 在 **diff** 阶段，尽可能复用了旧实例，导致列数据与预期的产生了差异。

可以在 *MyTable* 内部维护一个 `key` 去强制更新组件。

``` html
  <el-table ref="table">
    <children :key="key" />
  </el-table>
```

``` js
const key = ref(0)
watch(refactorSlot, () => {
  key.value += 1
})
```

> key 放 children 上或 el-table 上都可以

**Comment by aweikalee** [comment]
> 如果那列使用router-link，在后面再放开切换链接就消失了，是不是要重新渲染一下el-table

这是由 `KeepAlive` 引起的布局错误， *MyTable* 中在 `onActivated` 时调用 *el-table* 的 `doLayout` 方法即可。

```js
onActivated(() => {
  table.value?.doLayout()
})
```

**Comment by thinkwithlinc** [comment]
解决了，感谢
