### ISSUE TITLE
 如果type="selection"的时候el-table设置row-key属性,分页后第一页选中的数据,切换到第二页再切换来之前勾选的数据没了

### ISSUE THREAD

**Issue by baihuijun** [aweikalee/element-plus-table-proxy-demo#2]

**Comment by baihuijun** [comment]
![image](https://user-images.githubusercontent.com/52630363/209629569-07877bcb-2623-457c-ad63-5f50074f5f70.png)
![image](https://user-images.githubusercontent.com/52630363/209629600-b1b3c205-ff63-466b-97ac-a323da2f7f39.png)
![image](https://user-images.githubusercontent.com/52630363/209629690-2d974c01-05e2-4141-be9f-6c566f5549b6.png)

**Comment by aweikalee** [comment]
根据 `Element Plus` 文档所述，储存选中状态需要同时设置 `row-key` 与 `reserve-selection` 。
我这边测试并没有问题，是否是因为你没有设置 `reserve-selection` ？

**Comment by baihuijun** [comment]
感谢楼主百忙之中的回答,确实没设置reserve-selection属性☺
